name: open_social_share_example
description: Demonstrates how to use the open_social_share plugin.

publish_to: "none"

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  open_social_share:
    path: ../

  cupertino_icons: ^1.0.2
  file_picker: ^4.6.1
  image_picker: ^0.8.5+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
