name: open_social_share
description: A fork of the open_social_share open for everyone to update and improve.
version: 1.0.1
homepage: https://github.com/NazarenoCavazzon/open_social_share
repository: https://github.com/NazarenoCavazzon/open_social_share/issues

environment:
  sdk: ">=2.16.2 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: vn.open_social_share
        pluginClass: OpenSocialSharePlugin
      ios:
        pluginClass: OpenSocialSharePlugin
